services:
  flask_server:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    container_name: flask_server
    depends_on:
      - tika
    restart: always
    ports:
      - "5000:5000"
    networks:
      - tika_network

  tika:
    image: apache/tika:latest-full
    container_name: tika
    ports:
      - "${TIKA_PORT-9998}:9998"
    configs:
      - source: tika_config_3
        target: /tika-config.xml
    restart: unless-stopped
    networks:
      - tika_network
      
configs:
  tika_config_3:
    file: ./tika-config.xml

networks:
  tika_network:
    driver: bridge