services:
  flask_server:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${FLASK_SERVER_BASE_IMAGE:-rocm/pytorch:rocm6.4.1_ubuntu24.04_py3.12_pytorch_release_2.6.0}
    image: ${FLASK_SERVER_IMAGE:-flask_server:latest}
    container_name: ${FLASK_SERVER_CONTAINER_NAME:-flask_server}
    extra_hosts:
      - "host.docker.internal:host-gateway"  # For docker engine
    depends_on:
      - tika
      - rabbitmq
      - redis
    restart: always
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    networks:
      - tika_network
    environment:
      TIKA_URL: ${TIKA_URL:-http://tika:9998/tika}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://user:password@rabbitmq:5672//}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
      OLLAMA_URL: ${OLLAMA_URL:-http://ollama:11434/}
      POPPLER_PATH: ${POPPLER_PATH:-}
      MODEL_NAME: ${MODEL_NAME:-gemma3:4b}
      PORT: ${PORT:-8000}
      TAVILY_API_KEY: ${TAVILY_API_KEY:-placeholder_key}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-placeholder_key}
      BASE_URL: ${BASE_URL:-}
      GPU: ${GPU:-false}
    env_file:
      - .env
    volumes:
      - ${WORK_DIR:-./workdir}:/app/workdir
      - ${TRANSFORMERS_CACHE:-./transformers_cache}:/app/transformers_cache
    healthcheck:  # other containers dont have curl so this does them all
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-8000}/ || exit 1 && curl -f http://${TIKA_CONTAINER_NAME:-tika}:9998/tika || exit 1 && curl -f http://${RABBITMQ_CONTAINER_NAME:-rabbitmq}:15672/api/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  worker:
    image: ${WORKER_IMAGE:-flask_server:latest}
    container_name: ${WORKER_CONTAINER_NAME:-flask_worker}
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    depends_on:
      - flask_server
      - redis
      - tika
      - rabbitmq
    restart: always
    command: celery -A flask_server.celery:celery worker --loglevel=info
    environment:
      TIKA_URL: ${TIKA_URL:-http://tika:9998/tika}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://user:password@rabbitmq:5672//}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
      OLLAMA_URL: ${OLLAMA_URL:-http://host.docker.internal:11434/}
      POPPLER_PATH: ${POPPLER_PATH:-}
      MODEL_NAME: ${MODEL_NAME:-gemma3:4b}
      PORT: ${PORT:-8000}
      TAVILY_API_KEY: ${TAVILY_API_KEY:-placeholder_key}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-placeholder_key}
      BASE_URL: ${BASE_URL:-}
      GPU: ${GPU:-false}
    env_file:
      - .env
    networks:
      - tika_network
    volumes:
      - ${WORK_DIR:-./workdir}:/app/workdir
      - ${TRANSFORMERS_CACHE:-./transformers_cache}:/app/transformers_cache

  react_server:
    build: 
      context: ./react_server
      dockerfile: Dockerfile
    container_name: ${REACT_SERVER_CONTAINER_NAME:-react_server}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      TAVILY_API_KEY: ${TAVILY_API_KEY:-placeholder_key}
      MCP_API_KEY: ${MCP_API_KEY:-placeholder_key}
      READER_API: ${READER_API:-http://flask_server:8000/reader_api}
      READER_API_KEY: ${READER_API_KEY:-placeholder_key}
      MODEL_NAME: ${MODEL_NAME:-gemma3:4b}
      FLASK_SERVER_URL: ${FLASK_SERVER_URL:-http://flask_server:8000}
      OLLAMA_URL: ${OLLAMA_URL:-http://host.docker.internal:11434/}
      BASE_URL: ${BASE_URL:-}
    env_file:
      - .env
    networks:
      - tika_network
    depends_on:
      - flask_server

  tika:
    image: ${TIKA_IMAGE:-apache/tika:latest-full}
    container_name: ${TIKA_CONTAINER_NAME:-tika}
    ports:
      - "${TIKA_PORT:-9998}:9998"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ${TIKA_CONFIG_FILE:-./tika-config.xml}:/tika-config.xml
    networks:
      - tika_network

  rabbitmq:
    image: ${RABBITMQ_IMAGE:-rabbitmq:management}
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq}
    ports:
      - "${RABBITMQ_PORT_1:-5672}:5672"
      - "${RABBITMQ_PORT_2:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - tika_network

  redis:
    image: ${REDIS_IMAGE:-redis:latest}
    container_name: ${REDIS_CONTAINER_NAME:-redis}
    env_file:
      - .env
    ports:
      - "${REDIS_PORT:-6379}:6379"
    restart: unless-stopped
    networks:
      - tika_network

networks:
  tika_network:
    driver: bridge