services:
  flask_server:
    build:
      context: ./flask_server
      dockerfile: Dockerfile
    image: ${FLASK_SERVER_IMAGE:-flask_server:latest}
    container_name: ${FLASK_SERVER_CONTAINER_NAME:-flask_server}
    depends_on:
      - tika
      - rabbitmq
    restart: always
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    networks:
      - tika_network
    environment:
      TIKA_URL: ${TIKA_URL:-http://tika:9998/tika}
      RABBITMQ_URL: ${RABBITMQ_URL:-http://rabbitmq:15672/api/}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
      OLLAMA_URL: ${OLLAMA_URL:-http://ollama:11434/}
      POPPLER_PATH: ${POPPLER_PATH:-}
      TRANSFORMERS_CACHE: ${TRANSFORMERS_CACHE:-/tmp/transformers_cache}
      WORK_DIR: ${WORK_DIR:-/tmp/workdir}
      MODEL_NAME: ${MODEL_NAME:-gemma3:4b}
      PORT: ${PORT:-8000}
      TAVILY_KEY: ${TAVILY_KEY:-}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-supersecretkey}
    volumes:
      - ./openapi_spec.yaml:/app/flask_server/openapi_spec.yaml
    healthcheck:  # other containers dont have curl so this does them all
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-8000}/ || exit 1 && curl -f http://${TIKA_CONTAINER_NAME:-tika}:${TIKA_PORT:-9998}/tika || exit 1 && curl -f http://${RABBITMQ_CONTAINER_NAME:-rabbitmq}:${RABBITMQ_PORT_2:-15672}/api/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  worker:
    image: ${WORKER_IMAGE:-flask_server:latest}
    container_name: ${WORKER_CONTAINER_NAME:-flask_worker}
    depends_on:
      - flask_server
      - tika
      - rabbitmq
    restart: always
    command: celery -A flask_server.celery:celery worker --loglevel=info
    environment:
      TIKA_URL: ${TIKA_URL:-http://tika:9998/tika}
      RABBITMQ_URL: ${RABBITMQ_URL:-http://rabbitmq:15672/api/}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
      OLLAMA_URL: ${OLLAMA_URL:-http://ollama:11434/}
      POPPLER_PATH: ${POPPLER_PATH:-}
      TRANSFORMERS_CACHE: ${TRANSFORMERS_CACHE:-/tmp/transformers_cache}
      WORK_DIR: ${WORK_DIR:-/tmp/workdir}
      MODEL_NAME: ${MODEL_NAME:-gemma3:4b}
      PORT: ${PORT:-8000}
      TAVILY_KEY: ${TAVILY_KEY:-}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-supersecretkey}
    networks:
      - tika_network

  tika:
    image: ${TIKA_IMAGE:-apache/tika:latest-full}
    container_name: ${TIKA_CONTAINER_NAME:-tika}
    ports:
      - "${TIKA_PORT:-9998}:9998"
    restart: unless-stopped
    volumes:
      - ${TIKA_CONFIG_FILE:-./tika-config.xml}:/tika-config.xml
    networks:
      - tika_network

  rabbitmq:
    image: ${RABBITMQ_IMAGE:-rabbitmq:management}
    container_name: ${RABBITMQ_CONTAINER_NAME:-rabbitmq}
    ports:
      - "${RABBITMQ_PORT_1:-5672}:5672"
      - "${RABBITMQ_PORT_2:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-password}
    restart: unless-stopped
    networks:
      - tika_network

networks:
  tika_network:
    driver: bridge