openapi: 3.0.4
info:
  title: File Reader API
  description: Send files to the server and receive their content in a structured format.
  version: 1.0.0
servers:
  - url: http://localhost:8000 # Still in dev
tags:
  - name: file
    description: Operations related to file uploads
  - name: processing
    description: Operations related to processing uploaded files
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Form:
      type: object
      description: >
        A JSON object that specifies which fields to extract from the file, 
        and which type they should be. Valid values are: string, integer, 
        float, boolean, datetime, or array[type] of the previous types. 
        If the type is not specified, it defaults to string, and nested 
        objects are not supported.
      properties:
        filename:
          type: string
          description: The name of the file to process
        form:
          type: object
          description: A valid json object that specifies the fields to extract from the file
    HomeForm:
      type: object
      description: >
        Similar to a Form, with additional types: address and latlon
    DefaultHomeForm:
      type: object
      description: A default home form with fields for address and latlon
      properties:
        address:
          type: string
          description: The address of the home
        latlon:
          type: array
          items:
            type: number
          description: Latitude and longitude coordinates of the home
        year_built:
          type: integer
          description: The year the home was built
        square_footage:
          type: integer
          description: The total square footage of the home
        bedrooms:
          type: integer
          description: The number of bedrooms in the home
        bathrooms:
          type: integer
          description: The number of bathrooms in the home
        pool:
          type: boolean
          description: Whether the home has a pool or not
        garage:
          type: boolean
          description: Whether the home has a garage or not
    DefaultApplianceForm:
      type: object
      description: A default appliance form with fields for serial number and model number
      properties:
        serial_number:
          type: string
          description: The serial number of the appliance
        manufacturer:
          type: string
          description: The manufacturer of the appliance
        type:
          type: string
          description: The type of the appliance (e.g., refrigerator, washer, dryer)
paths:
  /:
    get:
      summary: Root endpoint
      description: This is the root endpoint of the File Reader API. It can be used to check if the server is running, and test the API.
      responses:
        '200':
          description: Server is running
          content:
            text/html:
              schema:
                type: string
                example: '<h1>File Reader API is running</h1>'
  /upload:
    post:
      tags:
        - file
      summary: Upload a file
      description: Upload a file to the server. Returns the filename for later processing.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Successful file upload
          content:
            application/json:
              schema:
                type: object
                properties:
                  filename:
                    type: string
                    description: The name of the uploaded file
        '400':
          description: Bad request, invalid file
        '500':
          description: Internal server error
  /process/txt:
    post:
      tags:
        - processing
      summary: Process a text file
      description: Process a previously uploaded text file and receive its content in a structured format.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: The name of the uploaded file
                form:
                  $ref: '#/components/schemas/Form'
      responses:
        '200':
          description: Successful response with file content
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    description: The extracted content from the text file
        '400':
          description: Bad request, invalid filename or form data
        '404':
          description: File not found
        '500':
          description: Internal server error
  /process/text:
    post:
      tags:
        - processing
      summary: Process a plain text request
      description: Process a plain text request and receive its content in a structured format. This route is useful for quick text processing without file uploads.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The plain text to process
                form:
                  $ref: '#/components/schemas/Form'
      responses:
        '200':
          description: Successful response with processed text content
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    description: The extracted content from the plain text
        '400':
          description: Bad request, invalid text or form data
        '500':
          description: Internal server error
  /process/ocr:
    post:
      tags:
        - processing
      summary: Process an image or PDF file for OCR
      description: Process a previously uploaded file for OCR. Returns the raw text content, unformatted.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: The name of the uploaded file
      responses:
        '200':
          description: Successful response with OCR content
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: The raw text content extracted from the file
        '400':
          description: Bad request, invalid filename
        '404':
          description: File not found
        '500':
          description: Internal server error
  /process/pdf:
    post:
      tags:
        - processing
      summary: Process a PDF file
      description: Process a previously uploaded PDF file and receive its content. This route does the analysis in one shot, so may be less accurate.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: The name of the uploaded file
                form:
                  $ref: '#/components/schemas/Form'
      responses:
        '200':
          description: Successful response with file content
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    description: The extracted content from the PDF file
        '400':
          description: Bad request, invalid filename or form data
        '404':
          description: File not found
        '500':
          description: Internal server error
  /process/home:
    post:
      tags:
        - processing
      summary: Process a home inspection report
      description: Process a previously uploaded home inspection report, along with a form, and parse the content into the form. Uses a default home form if no form is provided. Uses external services to fill in missing information if possible.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: The name of the uploaded file
                form:
                  $ref: '#/components/schemas/HomeForm'
      responses:
        '200':
          description: Successful response with home inspection report content
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    description: The extracted content from the home inspection report
        '400':
          description: Bad request, invalid filename or form data
        '404':
          description: File not found
        '500':
          description: Internal server error
  /process/appliance:
    post:
      tags:
        - processing
      summary: Process a photo of a manufacturer plate on an appliance
      description: Process a previously uploaded photo of a manufacturer plate on an appliance, along with a form, and parse the content into the form. Uses a default appliance form if no form is provided. Uses external services to fill in missing information if possible.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                filename:
                  type: string
                  description: The name of the uploaded file
                form:
                  $ref: '#/components/schemas/DefaultApplianceForm'
      responses:
        '200':
          description: Successful response with appliance information
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: object
                    description: The extracted content from the appliance photo
        '400':
          description: Bad request, invalid filename or form data
        '404':
          description: File not found
        '500':
          description: Internal server error
  /clear:
    post:
      tags:
        - file
      summary: Manually clear the uploaded files
      description: Clear all uploaded files from the server. This is useful for testing and development purposes.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully cleared uploaded files
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Confirmation message that files have been cleared
        '500':
          description: Internal server error